script: "bundle exec rake appraisal:integration test"
rvm:
  - 1.8.6
  - 1.8.7
  - 1.9.1
  - 1.9.2
env:
  - INTEGRATION=default TRAVIS=true
  - INTEGRATION=active_model TRAVIS=true
  - INTEGRATION=active_record TRAVIS=true
  - INTEGRATION=data_mapper TRAVIS=true
  - INTEGRATION=mongoid TRAVIS=true
  - INTEGRATION=mongo_mapper TRAVIS=true
  - INTEGRATION=sequel TRAVIS=true
notifications:
  disabled: true
